---
# This is the docker compose file to help with the creation of images
# The command bellow will help you clear out any lost docker containers
# docker kill `docker ps | grep pycloud_ | awk '{print $13}'`

version: '2'

services:
  pycloud:
    build: .
    image: year4000/pycloud
    container_name: y4k_pycloud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./pycloud/:/usr/local/lib/python3.6/site-packages/pycloud/
    depends_on:
      - redis
  redis:
    image: redis
    container_name: y4k_redis
    ports:
      - 6379:6379
