# PyCloud Settings

# The region this node is opperating on
region: "pycloud"

# The address to use in pycloud.json, blank for system default
hostname:

# The redis connection host, port, and password
redis:
  host: "localhost"
  port: 6379
  password:
